# Installs Claude Code user-level CLAUDE.md, assembled from a base fragment (in prat) plus optional additional fragments.
function Install-ClaudeUserConfig {
    [CmdletBinding()]
    param ($stage, [string[]] $fragmentPaths)
    $destFile = "$home\.claude\CLAUDE.md"

    $content = "<!-- Auto-generated by Prat deployment. Edit the source fragments, not this file. -->`n`n"

    $content += Import-TextFile "$PSScriptRoot\..\agents\agent-user_prat.md"

    foreach ($path in $fragmentPaths) {
        $content += "`n`n"
        $content += Import-TextFile $path
    }

    Install-TextToFile $stage $destFile $content -SetReadOnly -ShowUpdateDetails:($VerbosePreference -eq 'Continue')
}

# Install Claude Code skills into a target .claude/skills directory.
# Deployed files get an auto-generated header and are set read-only to discourage editing the deployed copy.
# Skills not in any set are removed from $destDir.
#
#   Install-ClaudeSkillSet $stage @(
#       @{ set = @("skill-a"); srcDir = "path/to/skills1" }
#       @{ set = @("skill-b"); srcDir = "path/to/skills2" }
#   ) $destDir
function Install-ClaudeSkillSet($stage, $sources, [string] $destDir) {
    $headerText = "Auto-generated by Prat deployment. Edit the source skill file, not this deployed copy."
    $htmlHeader = "<!-- $headerText -->"
    $hashHeader = "# $headerText"

    $entries = @($sources)
    $allNames = @()
    foreach ($entry in $entries) {
        $entrySet = $entry.set
        $entrySrcDir = $entry.srcDir
        $srcNames = (Get-ChildItem -Directory $entrySrcDir).Name
        foreach ($name in $entrySet) {
            if ($name -notin $srcNames) { throw "Skill '$name' not found in $entrySrcDir" }
        }
        $allNames += $entrySet
    }

    Install-Folder $stage $destDir
    foreach ($entry in $entries) {
        foreach ($skillDir in Get-ChildItem -Directory $entry.srcDir) {
            if ($entry.set -contains $skillDir.Name) {
                $destSkillDir = Join-Path $destDir $skillDir.Name
                Install-Folder $stage $destSkillDir
                foreach ($file in Get-ChildItem -File $skillDir.FullName) {
                    # Skip test files; they're for source-side validation, not deployment.
                    if ($file.Name -like '*.Tests.ps1') { continue }

                    # Pick comment syntax by extension. PowerShell and Python need `#`; markdown/HTML use `<!-- -->`.
                    $header = switch -Wildcard ($file.Extension.ToLower()) {
                        '.ps1'  { $hashHeader }
                        '.psm1' { $hashHeader }
                        '.psd1' { $hashHeader }
                        '.py'   { $hashHeader }
                        default { $htmlHeader }
                    }

                    $content = Import-TextFile (Join-Path $skillDir.FullName $file.Name)
                    if ($content -match '(?s)^(---\r?\n.*?\r?\n---\r?\n)') {
                        $frontmatter = $matches[1]
                        $body = $content.Substring($frontmatter.Length)
                        $newContent = $frontmatter + "`n" + $header + "`n`n" + $body
                    } else {
                        $newContent = $header + "`n`n" + $content
                    }
                    Install-TextToFile $stage (Join-Path $destSkillDir $file.Name) $newContent -SetReadOnly
                }
            }
        }
    }
    foreach ($destSkillDir in Get-ChildItem -Directory $destDir -ErrorAction SilentlyContinue) {
        if ($destSkillDir.Name -notin $allNames) {
            $stage.OnChange()
            Remove-Item $destSkillDir.FullName -Recurse -Force
        }
    }
}

# Install Claude Code agents or commands from a flat directory of .md files into a target
# .claude/agents or .claude/commands directory.
# Places the auto-generated header after YAML frontmatter (if present) so that YAML parsing
# is not broken by a leading comment.
function Install-ClaudeMarkdownFiles($stage, [string] $srcDir, [string] $destDir, [switch] $Cleanup) {
    $header = "<!-- Auto-generated by Prat deployment. Don't edit this copy - any edits will just be overwritten. -->"
    Install-Folder $stage $destDir
    foreach ($file in Get-ChildItem -File $srcDir) {
        $content = Import-TextFile (Join-Path $srcDir $file.Name)
        if ($content -match '(?s)^(---\r?\n.*?\r?\n---\r?\n)') {
            $frontmatter = $matches[1]
            $body = $content.Substring($frontmatter.Length)
            $newContent = $frontmatter + "`n" + $header + "`n`n" + $body
        } else {
            $newContent = $header + "`n`n" + $content
        }
        Install-TextToFile $stage (Join-Path $destDir $file.Name) $newContent -SetReadOnly
    }
    if ($Cleanup) {
        $sourceNames = (Get-ChildItem -File $srcDir).Name
        foreach ($destFile in Get-ChildItem -File $destDir -ErrorAction SilentlyContinue) {
            if ($destFile.Name -notin $sourceNames) {
                $stage.OnChange()
                Set-ItemProperty $destFile.FullName -Name IsReadOnly -Value $false -ErrorAction SilentlyContinue
                Remove-Item $destFile.FullName -Force
            }
        }
    }
}

# Sync the .claude/plan folder to a sync folder (OneDrive, Dropbox, etc.)
# using a directory junction.
#
# $syncRoot: The sync folder root for claude data, e.g. "$home\OneDrive\.claude-sync"
# $claudeDir: Override for testing. Defaults to "$home\.claude".
function Install-ClaudeSyncFolders($stage, [string] $syncRoot, [string] $claudeDir = "$home\.claude") {
    $syncDirs = @("plans")

    Install-SyncFolders $stage ".claude" $claudeDir $syncRoot $syncDirs
}

# Installs a read-only MEMORY.md into every Claude Code project memory directory found under $claudeDir,
# redirecting the auto-memory feature to source-controlled files instead.
#
# Won't overwrite an existing custom MEMORY.md - instead will warn and skip.
function Install-ClaudeProjectMemory {
    param($stage, [string] $claudeDir = "$home\.claude")

    $header = "<!-- Auto-generated by Prat deployment. Do not edit — see source. -->"
    $content = $header + "`n`n" + (Import-TextFile "$PSScriptRoot\..\agents\memory-template.md")

    $projectsDir = Join-Path $claudeDir "projects"
    if (-not (Test-Path $projectsDir)) { return }

    foreach ($projectDir in Get-ChildItem -Directory $projectsDir -ErrorAction SilentlyContinue) {
        $memoryDir  = Join-Path $projectDir.FullName "memory"
        $memoryFile = Join-Path $memoryDir "MEMORY.md"

        if (Test-Path $memoryFile) {
            $existing = Get-Content $memoryFile -Raw -ErrorAction SilentlyContinue
            if ($existing -notlike "$header*") {
                Write-Warning "Skipping $memoryFile — has non-generated content. Review and delete manually."
                continue
            }
        }

        Install-Folder $stage $memoryDir
        Install-TextToFile $stage $memoryFile $content -SetReadOnly
    }
}

# Installs Claude Code user-level settings.json. For now just a copy, may need merging later.
# Wraps Install-LocalAgentSandbox with Claude-specific config sharing: junction for .claude/,
# symlinks for .claude.json and .claude.json.backup. The two json files are automatically added
# to rwPaths so permissions are granted and {} placeholders created if not yet present.
#
# .PARAMETER claudeHome
# Home directory of the user whose Claude config the agent should share.
function Install-ClaudeAgentSandbox {
    [CmdletBinding()]
    param(
        $stage,
        [string] $agentUser,
        [string] $claudeHome,
        [string[]] $rwPaths = @(),
        [string[]] $roPaths = @(),
        [string[]] $safeDirectories = @(),
        [hashtable] $homeJunctions = @{},
        [string] $profileContent = $null,
        [string] $sshPublicKeyPath = $null
    )

    $claudeHome = $claudeHome -replace '/', '\'

    Install-LocalAgentSandbox $stage `
        -agentUser       $agentUser `
        -rwPaths         ($rwPaths + @("$claudeHome\.claude", "$claudeHome\.claude.json.backup")) `
        -roPaths         ($roPaths + @("$claudeHome\.local\bin")) `
        -safeDirectories $safeDirectories `
        -homeJunctions   $homeJunctions `
        -profileContent  $profileContent `
        -sshPublicKeyPath $sshPublicKeyPath

    # Create junction and symlinks after Install-LocalAgentSandbox has set ACLs and ensured targets exist.
    $agentHome = "$env:SystemDrive\Users\$agentUser"

    $jLink = "$agentHome\.claude"
    $jItem = Get-Item $jLink -ErrorAction SilentlyContinue
    if ($null -eq $jItem -or $jItem.LinkType -ne 'Junction') {
        $stage.OnChange()
        $jTarget = "$claudeHome\.claude"
        if ($null -ne $jItem) { Invoke-Gsudo { Remove-Item -Force -Recurse $using:jLink } }
        Invoke-Gsudo { New-Item -ItemType Junction -Path $using:jLink -Target $using:jTarget | Out-Null }
    }

    # .claude.json is intentionally NOT symlinked: Start-CommandLineAgent.ps1 removes and
    # re-copies .claude.json at each launch (to refresh auth), so a symlink here would be
    # replaced with a regular file on every cl invocation, causing spurious deploy updates.
    foreach ($fileName in @('.claude.json.backup')) {
        $sLink = "$agentHome\$fileName"
        $sItem = Get-Item $sLink -ErrorAction SilentlyContinue
        if ($null -eq $sItem -or $sItem.LinkType -ne 'SymbolicLink') {
            $stage.OnChange()
            $sTarget = "$claudeHome\$fileName"
            if ($null -ne $sItem) { Invoke-Gsudo { Remove-Item -Force $using:sLink } }
            Invoke-Gsudo { New-Item -ItemType SymbolicLink -Path $using:sLink -Target $using:sTarget | Out-Null }
        }
    }

    # Junction .local\bin to the managing user's — ensures agent always runs the current version
    # and can't accumulate a stale separate copy (agent has RX on the target via roPaths).
    $localBin       = "$agentHome\.local\bin"
    $localBinTarget = "$claudeHome\.local\bin"
    $null = New-Item -ItemType Directory -Path "$agentHome\.local" -ErrorAction SilentlyContinue
    $jItem = Get-Item $localBin -ErrorAction SilentlyContinue
    if ($null -eq $jItem -or $jItem.LinkType -ne 'Junction') {
        $stage.OnChange()
        if ($null -ne $jItem) { Remove-Item -Force -Recurse $localBin }
        New-Item -ItemType Junction -Path $localBin -Target $localBinTarget | Out-Null
    }

    # Grant add-subdirectory right on claudeHome so CC can create .claude.lock as a token-refresh
    # mutex. andrew_agent owns the dir it creates, so no Delete ACE on the parent is needed.
    # (AD) only — does not grant file creation, listing, or access to existing items.
    if (-not $stage.GetIsStepComplete("claudeAgentSandbox/lockGrant/$agentUser")) {
        $lockGrant = "${agentUser}:(AD)"
        Invoke-Gsudo {
            icacls $using:claudeHome /grant:r $using:lockGrant | Out-Null
            if ($LASTEXITCODE -ne 0) { throw "icacls failed for $using:claudeHome (exit $LASTEXITCODE)" }
        }
        $stage.SetStepComplete("claudeAgentSandbox/lockGrant/$agentUser")
    }
}

function Install-ClaudeUserSettings($stage, [string] $claudeDir = "$home\.claude") {
    $destFile = "$claudeDir\settings.json"

    $sourceFiles = @(Resolve-PratLibFile "lib/inst/Get-ClaudeUserSettings.ps1" -ListAll)
    if ($sourceFiles.Count -eq 0) { throw "No Get-ClaudeUserSettings scripts found in dev environment chain" }

    $merged = @{}
    foreach ($file in $sourceFiles) {
        $layer = & $file
        $merged = Merge-DeepHashtable $merged $layer
    }

    $merged["_comment"] = "Auto-generated by Prat deployment. Edit the source scripts, not this file."
    $newText = ConvertTo-Json $merged -Depth 20

    # We don't set read-only on this file, because Claude Code wants to write it - it records UI/session changes.
    Install-JsonToFile $stage $destFile $newText
}

