# Resolves layer agent-user.md fragments in base-first order (prat → prefs → de).
function Get-HarnessUserFragments {
    $fragments = @(Resolve-PratLibFile 'lib/agents/agent-user.md' -ListAll)
    [array]::Reverse($fragments)
    return $fragments
}

# Installs a harness user instructions file, assembled from registered fragments.
function Install-HarnessUserInstructions {
    [CmdletBinding()]
    param ($stage, [string] $destFile, [string[]] $fragmentPaths)

    $content = "<!-- Auto-generated by Prat deployment. Edit the source fragments, not this file. -->`n`n"

    foreach ($path in $fragmentPaths) {
        $content += Import-TextFile $path
        $content += "`n`n"
    }

    Install-TextToFile $stage $destFile $content -SetReadOnly -ShowUpdateDetails:($VerbosePreference -eq 'Continue')
}

function Install-HarnessIntegration {
    param($stage, [string] $harness, [string[]] $Suppress = @(), [string[]] $Enable = @(), [hashtable] $Config = @{})
    switch ($harness) {
        'claude'  { Install-ClaudeHarness  $stage -Suppress $Suppress -Enable $Enable -Config $Config }
        'copilot' { Install-CopilotHarness $stage }
        default   { throw "Unknown harness: '$harness'" }
    }
}
