#
# Module manifest for module 'TextFileEditor'
#
# Generated by: Andrew Godfrey
#
# Generated on: 4/3/2024
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'TextFileEditor.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# ID used to uniquely identify this module
GUID = '85be811c-8762-4fb7-bcb4-47155737300a'

# Author of this module
Author = 'Andrew Godfrey'

# Copyright statement for this module
Copyright = 'Copyright (c) 2024 Andrew Godfrey'

# Description of the functionality provided by this module
Description = 'Tools for in-memory editing of a text file, in a line-oriented way'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
	'Import-TextFile', 'Format-IndentLine', 'Format-ReplaceLines', 'Read-Lines', 'Add-Lines',
	'Find-XmlSection', 'Update-XmlSection',
	'Get-IndentLevel', 'Find-MatchingLine', 'Find-CorrespondingIndent', 'Get-SubIndent', 'Format-ReplaceMatchingLines',
	'Test-IsSingleLinePowershellBlock', 'Find-MatchingPowershellBlock', 'Add-HashTableItemInPowershellScript', 'Test-HashTableItemInPowershellScript', 'Edit-HashOfArraysItemInPowershellScript',
	'Update-PatchSlickOpenWkspace'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/AndrewGodfrey/prat/blob/main/LICENSE'

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

